function update_plot_mhe(vec, ph)
% This function updates the MHE plot. The figure specified via the plot
% handle ph must have been generated by the function init_plot_mhe.
%
% Input arguments are:
% 1) vec - struct with time, inputs, states and outputs
% 2) ph - plot handle generated by init_plot_mhe
%
%
% This file is part of GRAMPC - (https://github.com/grampc/grampc)
%
% GRAMPC -- A software framework for embedded nonlinear model predictive
% control using a gradient-based augmented Lagrangian approach
%
% Copyright 2014-2025 by Knut Graichen, Andreas Voelz, Thore Wietzke,
% Tobias Englert (<v2.3), Felix Mesmer (<v2.3), Soenke Rhein (<v2.3),
% Bartosz Kaepernick (<v2.0), Tilman Utz (<v2.0).
% All rights reserved.
%
% GRAMPC is distributed under the BSD-3-Clause license, see LICENSE.txt

% Inputs
for i = 1 : size(vec.u, 1)
    set(ph.s1(i), 'XData', vec.t);
    set(ph.s1(i), 'YData', vec.u(i,:));
end
adapt_ylim(vec.u, ph.s1);

% States
for i = 1 : size(vec.x, 1)
    set(ph.s2(i), 'XData', vec.t);
    set(ph.s2(i), 'YData', vec.x(i,:));

    set(ph.s3(i), 'XData', vec.t);
    set(ph.s3(i), 'YData', vec.xest(i,:));
end
adapt_ylim([vec.x; vec.xest], ph.s2);

% Outputs
for i = 1 : size(vec.y, 1)
    set(ph.s4(i), 'XData', vec.t);
    set(ph.s4(i), 'YData', vec.y(i,:));

    set(ph.s5(i), 'XData', vec.t);
    set(ph.s5(i), 'YData', vec.yest(i,:));

    set(ph.s6(i), 'XData', vec.t);
    set(ph.s6(i), 'YData', vec.ymeas(i,:));
end
adapt_ylim([vec.y; vec.yest; vec.ymeas], ph.s4);

end
