[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "template"
version = "1.0"
description="Template problem for GRAMPC"

[tool.scikit-build]
wheel.expand-macos-universal-tags = true
